### ISSUE TITLE
showコマンドの結果がクソ長になる

### ISSUE THREAD

**Issue by hutinoatari** [Azuki-bar/ceviord#30]
showコマンドの後ろに数字を指定して10刻みで表示できるようにしませんか？
```txt
> !dict show 3
39 jjj
(中略)
30 aaa
```

**Comment by Azuki-bar** [comment]
本件ですが以下のようにコマンドを整備することとしました。

- `!dict show` で直近10レコード表示。 `!dict show 10`と等価
- `!dict show N`で直近Nレコード表示。
- `!dict show all`で全てのレコードを表示
- `!dict show N M`でidがNからMまでのレコード表示
